version: 2
updates:
  - package-ecosystem: "nuget"
    open-pull-requests-limit: 2
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"